# Setup
title:        Airizse 
tagline:      a baneling
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Airizse
  url:        https://airizse.github.io/ 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown